# Generated by Django 4.0.4 on 2022-05-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Корзина покупателя', 'verbose_name_plural': 'Корзины покупателей'},
        ),
    ]
