# Generated by Django 4.1.2 on 2022-12-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_historicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCoupon',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('condition', models.TextField(verbose_name='Условия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Старая цена')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Новая цена')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('photo', models.TextField(max_length=100, verbose_name='Фото')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Купон',
                'verbose_name_plural': 'historical Купоны',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
